FROM python:3.11-slim-bookworm

# Set the working directory to /app
WORKDIR /EyeQ

# Copy the current directory contents into the container at /app
COPY . ./

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN chmod +x selector.sh
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME bio_project

# Run app.py when the container launches
ENTRYPOINT ["./selector.sh"]



